services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/tmp/uploads
    depends_on:
      - db
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - DATABASE_URL=${DATABASE_URL}
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
